# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02280f3eed419e6df944cf050cc390907da7e34fe86b49e01f8b4ba70a48ad2a7df5172633dc265258a666fc7ff323dff715c9357cb64808f105f3f011dd4550

test:
  secret_key_base: 0383061c5b1258335c6f6db4cd4622ea4f7e596ba4f6c7cfcd605f5cd7fe9bf1015ba1fe23beb061a6a457e30b24b6b403df716138bd2a7f140a993a3a8b8172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 02280f3eed419e6df944cf050cc390907da7e34fe86b49e01f8b4ba70a48ad2a7df5172633dc265258a666fc7ff323dff715c9357cb64808f105f3f011dd4550
